repos:
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: ["--config=pre_commit_configs/black.cfg"]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--settings-path=pre_commit_configs/isort.toml"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--config=pre_commit_configs/flake8.cfg"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: ['--config-file', 'pre_commit_configs/mypy.cfg', '--show-traceback']
        name: mypy
        additional_dependencies:
          - "pydantic>=2.6.3"